# Generated by Django 4.1 on 2024-04-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("bookno", models.IntegerField(primary_key=True, serialize=False)),
                ("bookname", models.CharField(max_length=20)),
                ("author", models.CharField(max_length=20)),
                ("pages", models.IntegerField()),
                ("published_date", models.DateField()),
                ("bookprice", models.IntegerField()),
            ],
        ),
    ]
